name: style
on: push

jobs:
  Style-Check-Src-Files:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ–Œï¸ Analizando e corrigindo cÃ³digo para encontrar erros de estilo."
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4

      - run: |
          npm i
          npx prettier . --check
