name: style
on: push

jobs:
  Style-Check-Src-Files:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ–Œï¸ Analizando e corrigindo cÃ³digo para encontrar erros de estilo."
      
      - name: ğŸ”¦ Checkout
        uses: actions/checkout@v4
        
      - name: ğŸ§° Setup node
        uses: actions/setup-node@v4

      - name: ğŸ¨ prettier
        run: |
          npm i
          npx prettier . --check

      - if: failure()
        run: echo "ğŸš« O prettier encotrou erros de estilo" && echo "Use o comando 'npx prettier . --write' para corrigir automaticamente"
